name: yolo_skin
description: An app to solve your acne problem
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  pytorch_mobile: ^0.2.2

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  freezed_annotation: ^2.0.3
  json_serializable: ^6.3.1
  # mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    # - assets/faces.pt
    - assets/face.torchscript
    - assets/labels.csv
    - assets/dummy_result.jpeg
    - assets/dummy_result2.jpeg
